### ISSUE TITLE
Add compilation of Review articles

### ISSUE THREAD

**Issue by ofou** [NeuroTechX/awesome-bci#48]
I just found a [list](https://github.com/okbalefthanded/awesome-bci-reviews) of relevant BCIs review papers. I may be relevant to add a link to the articles list. 
What do you think guys?

**Comment by alexfigtree** [comment]
@ofou A link would be great. You can put it under Reading Material or Other Sources. Please submit a PR.

**Comment by obrunodelgado** [comment]
I have opened a Pull Request to resolve this issue

https://github.com/NeuroTechX/awesome-bci/pull/67
