### ISSUE TITLE
Pls modify Open Neuroscience link

### ISSUE THREAD

**Issue by alchemiker** [NeuroTechX/awesome-bci#51]
The last link of the awesome-bci list,  Open Neuroscience [https://open-neuroscience.com/en/](https://open-neuroscience.com/en/) leads to _404 page not found_. Their homepage is [https://open-neuroscience.com](https://open-neuroscience.com). 
I cannot edit in this repo, but I think it should be easy to fix for you.

**Comment by alexfigtree** [comment]
@alchemiker You can also submit changes via PR using GitHub's web-based editor.

**Comment by obrunodelgado** [comment]
I have opened this Pull Request to solve this issue

https://github.com/NeuroTechX/awesome-bci/pull/67
