### ISSUE TITLE
Link led to malicious(?) website

### ISSUE THREAD

**Issue by stack690** [NeuroTechX/awesome-bci#55]
https://github.com/NeuroTechX/awesome-bci#consultants-for-hire
The website mentioned here(http ://www.pushtheworld.us/) led to a redirecting storm.
I'm pretty sure that is a malicious or overtaken website.
Please check.
By the way, I also checked it on VirusTotal;
https://www.virustotal.com/gui/url/bba993573aac43c7a64b315f7d052841ab40e36c61aedf63a8b777f3d2bc8cdf?nocache=1

**Comment by NickShargan** [comment]
The malicious link is still there.

**Comment by alexfigtree** [comment]
@NickShargan Thanks for letting us know. @andrewjaykeller Could you please take a look at your site?

**Comment by alexfigtree** [comment]
@stack690 @NickShargan If this is still an issue, we welcome a PR removing this link. Thank you.

**Comment by andrewjaykeller** [comment]
Please remove the link!

**Comment by stack690** [comment]
@alexfigtree
Review&Merging would be appreciated.
